### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Matr1x-101** [aidens113/swagbucks_auto_survey#1]
Whenever I run the code with python3, I get these errors: 
When I input >1 threads:
```
Traceback (most recent call last):
  File "/Users/username/swagbucks_auto_survey/bot.py", line 1155, in <module>
    threads(int(amnt))
  File "/Users/username/swagbucks_auto_survey/bot.py", line 1122, in threads
    threads.append(threading.Thread(target=main,args=[i,proxies[i],]))
IndexError: list index out of range
```
When I input 1 threads:
The following console output endlessly loops:
```
Error: list index out of range
proxy
```

Please fix this.

**Comment by aidens113** [comment]
Please read the code. It needs to be changed for your specific situation. If you're copy & pasting then this code is not for you.
